# Generated by Django 6.1 on 2026-08-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.moto')),
            ],
        ),
        migrations.CreateModel(
            name='oleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('kms', models.IntegerField()),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.moto')),
            ],
        ),
        migrations.CreateModel(
            name='washed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.moto')),
            ],
        ),
    ]
